// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHb7UdHEW2QMrXTtUwlTS6X428P8wvWx8',
    appId: '1:1052699764012:web:d6f513e1b701a5962d7889',
    messagingSenderId: '1052699764012',
    projectId: 'my-fitness010',
    authDomain: 'my-fitness010.firebaseapp.com',
    storageBucket: 'my-fitness010.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPnKF0Hr8gzmtxsbA72vd6a31hCp6aVCA',
    appId: '1:1052699764012:android:430775d48e6c7f522d7889',
    messagingSenderId: '1052699764012',
    projectId: 'my-fitness010',
    storageBucket: 'my-fitness010.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOGpSpwQOXER9GcU1Z2jnu57KffW1-zcg',
    appId: '1:1052699764012:ios:83cf47dd595929852d7889',
    messagingSenderId: '1052699764012',
    projectId: 'my-fitness010',
    storageBucket: 'my-fitness010.firebasestorage.app',
    iosBundleId: 'com.example.fyp',
  );
}
